# Generated by Django 2.0 on 2019-10-26 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_company', models.CharField(blank=True, max_length=100)),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('job_body', models.TextField(blank=True)),
                ('job_url', models.TextField(blank=True)),
                ('job_source', models.CharField(blank=True, max_length=30)),
                ('job_location', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('favorite', models.ManyToManyField(blank=True, related_name='favorite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='posting',
            name='favorite',
        ),
        migrations.DeleteModel(
            name='Posting',
        ),
    ]
